### PR TITLE
Merges latest testcafe to our fork

### PR DESCRIPTION
**Pull request by franciscolosardo**
## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

**Comment by rob4629** [comment]
> Thanks for the contribution! Before we can merge this, we need @DIRECTcut @Aleksey28 @AlexKamaev @wentwrong @AndreyBelym @VasilyStrelyaev @rob4629 @Farfurix @miherlosev to [sign the Salesforce.com Contributor License Agreement](https://cla.salesforce.com/sign-cla?prUrl=https%3A%2F%2Fgithub.com%2Fmulesoft-labs%2Ftestcafe%2Fpull%2F6).

~I tried to sign, but was presented with an error: `Could not sign the CLA, please contactoss-cla@salesforce.com`~ 2nd attempt results in a duplication error... so I'm assuming the original has worked
Screenshot 2021-12-06 at 12 46 33 PM

**Comment by felis2803** [comment]
@iamerico Please disable the salesforce-cla bot or set it to stop spamming.

**Comment by felis2803** [comment]
@iamerico, @iglosiggio, @mulesoft-labs Please stop spam from this pull request.

**Comment by iglosiggio** [comment]
> @iamerico, @iglosiggio, @mulesoft-labs Please stop spam from this pull request.

I'm not remotely related to this fork.

Will close the PR though. It looks like an old attempt to re-sync the fork with the master branch.

**Pull request closed without merging**
